# -*- coding: cp1252 -*-
# Tabular page
def cont2():
    time.sleep(1)
    import tkMessageBox
    top=Tk()
    top.configure(height=10000,width=5678)
    # Group 1
    def b1():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Hydrogen.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="30")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b2():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Lithium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b3():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Sodium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b4():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Potassium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b5():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Rubidium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b6():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Caesium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b7():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Francium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 2
    def b8():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Beryllium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b9():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Magnesium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b10():
        t=open("D:\Study Material\Projects\Class XI Python Project\Calcium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b11():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Strontium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b12():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Barium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b13():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Radium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 3
    def b14():
        t=open("C:\Users\office\Desktop\Files\Scandium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b15():
        t=open("C:\Users\office\Desktop\Files\Yttrium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b16():
        t=open("C:\Users\office\Desktop\Files\Lutetium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b17():
        t=open("C:\Users\office\Desktop\Files\Lawrencium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 4
    def b18():
        t=open("C:\Users\office\Desktop\Files\Titanium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b19():
        t=open("C:\Users\office\Desktop\Files\Zirconium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b20():
        t=open("C:\Users\office\Desktop\Files\Hafnium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b21():
        t=open("C:\Users\office\Desktop\Files\Rutherfordium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 5
    def b22():
        t=open("C:\Users\office\Desktop\Files\Vanadium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b23():
        t=open("C:\Users\office\Desktop\Files\Niobium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b24():
        t=open("C:\Users\office\Desktop\Files\Tantalum.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b25():
        t=open("C:\Users\office\Desktop\Files\Dubnium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 6
    def b26():
        t=open("C:\Users\office\Desktop\Files\Chromium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b27():
        t=open("C:\Users\office\Desktop\Files\Molybdenum.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b28():
        t=open("C:\Users\office\Desktop\Files\Tungsten.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b29():
        t=open("C:\Users\office\Desktop\Files\Seaborgium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 7
    def b30():
        t=open("C:\Users\office\Desktop\Files\Manganese.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b31():
        t=open("C:\Users\office\Desktop\Files\Technetium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b32():
        t=open("C:\Users\office\Desktop\Files\Rhenium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b33():
        t=open("C:\Users\office\Desktop\Files\Bohrium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 8
    def b34():
        t=open("C:\Users\office\Desktop\Files\Iron.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b35():
        t=open("C:\Users\office\Desktop\Files\Ruthenium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b36():
        t=open("C:\Users\office\Desktop\Files\Osmium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b37():
        t=open("C:\Users\office\Desktop\Files\Hassium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 9
    def b38():
        t=open("C:\Users\office\Desktop\Files\Cobalt.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b39():
        t=open("C:\Users\office\Desktop\Files\Rhodium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b40():
        t=open("C:\Users\office\Desktop\Files\Iridium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b41():
        t=open("C:\Users\office\Desktop\Files\Meitnerium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 10
    def b42():
        t=open("C:\Users\office\Desktop\Files\Nickel.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b43():
        t=open("C:\Users\office\Desktop\Files\Palladium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b44():
        t=open("C:\Users\office\Desktop\Files\Platinum.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b45():
        t=open("C:\Users\office\Desktop\Files\Darmstadtium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 11
    def b46():
        t=open("C:\Users\office\Desktop\Files\Copper.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b47():
        t=open("C:\Users\office\Desktop\Files\Silver.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b48():
        t=open("C:\Users\office\Desktop\Files\Gold.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b49():
        t=open("C:\Users\office\Desktop\Files\Roentgenium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 12
    def b50():
        t=open("C:\Users\office\Desktop\Files\Zinc.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b51():
        t=open("C:\Users\office\Desktop\Files\Cadmium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b52():
        t=open("C:\Users\office\Desktop\Files\Mercury.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b53():
        t=open("C:\Users\office\Desktop\Files\Copernicium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="83",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 13
    def b54():
        t=open("C:\Users\office\Desktop\Files\Boron.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b55():
        t=open("C:\Users\office\Desktop\Files\Aluminium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="44")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b56():
        t=open("C:\Users\office\Desktop\Files\Gallium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b57():
        t=open("C:\Users\office\Desktop\Files\Indium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b58():
        t=open("C:\Users\office\Desktop\Files\Thallium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b59():
        t=open("C:\Users\office\Desktop\Files\Ununtrium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 14
    def b60():
        t=open("C:\Users\office\Desktop\Files\Carbon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b61():
        t=open("C:\Users\office\Desktop\Files\Silicon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="44")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b62():
        t=open("C:\Users\office\Desktop\Files\Germanium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b63():
        t=open("C:\Users\office\Desktop\Files\Tin.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b64():
        t=open("C:\Users\office\Desktop\Files\Lead.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b65():
        t=open("C:\Users\office\Desktop\Files\Flerovium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack() 
        root.mainloop()
    # Group 15
    def b66():
        t=open("C:\Users\office\Desktop\Files\Nitrogen.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b67():
        t=open("C:\Users\office\Desktop\Files\Phosphorous.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="67",height="44")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b68():
        t=open("C:\Users\office\Desktop\Files\Arsenic.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="70",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b69():
        t=open("C:\Users\office\Desktop\Files\Antimony.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b70():
        t=open("C:\Users\office\Desktop\Files\Bismuth.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b71():
        t=open("C:\Users\office\Desktop\Files\Ununpentium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="62",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 16
    def b72():
        t=open("C:\Users\office\Desktop\Files\Oxygen.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b73():
        t=open("C:\Users\office\Desktop\Files\Sulphur.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="67",height="44")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b74():
        t=open("C:\Users\office\Desktop\Files\Selenium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b75():
        t=open("C:\Users\office\Desktop\Files\Tellurium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b76():
        t=open("C:\Users\office\Desktop\Files\Polonium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b77():
        t=open("C:\Users\office\Desktop\Files\Livermorium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 17
    def b78():
        t=open("C:\Users\office\Desktop\Files\Fluorine.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="70",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b79():
        t=open("C:\Users\office\Desktop\Files\Chlorine.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="68",height="44")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b80():
        t=open("C:\Users\office\Desktop\Files\Bromine.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="43")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b81():
        t=open("C:\Users\office\Desktop\Files\Iodine.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b82():
        t=open("C:\Users\office\Desktop\Files\Astatine.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="69",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b83():
        t=open("C:\Users\office\Desktop\Files\Ununseptium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Group 18
    def b84():
        t=open("C:\Users\office\Desktop\Files\Helium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b85():
        t=open("C:\Users\office\Desktop\Files\Neon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b86():
        t=open("C:\Users\office\Desktop\Files\Argon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b87():
        t=open("C:\Users\office\Desktop\Files\Krypton.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b88():
        t=open("C:\Users\office\Desktop\Files\Xenon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b89():
        t=open("C:\Users\office\Desktop\Files\Radon.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b90():
        t=open("C:\Users\office\Desktop\Files\Ununoctium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Lanthanoids
    def b91():
        t=open("C:\Users\office\Desktop\Files\Lanthanum.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b92():
        t=open("C:\Users\office\Desktop\Files\Cerium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b93():
        t=open("C:\Users\office\Desktop\Files\Praseodymium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="68",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b94():
        t=open("C:\Users\office\Desktop\Files\Neodymium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b95():
        t=open("C:\Users\office\Desktop\Files\Promethium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b96():
        t=open("C:\Users\office\Desktop\Files\Samarium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b97():
        t=open("C:\Users\office\Desktop\Files\Europium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b98():
        t=open("C:\Users\office\Desktop\Files\Gadolinium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b99():
        t=open("C:\Users\office\Desktop\Files\Terbium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b100():
        t=open("C:\Users\office\Desktop\Files\Dysprosium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b101():
        t=open("C:\Users\office\Desktop\Files\Holmium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b102():
        t=open("C:\Users\office\Desktop\Files\Erbium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b103():
        t=open("C:\Users\office\Desktop\Files\Thulium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b104():
        t=open("C:\Users\office\Desktop\Files\Ytterbium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="63",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    # Actinoids
    def b105():
        t=open("C:\Users\office\Desktop\Files\Actinium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b106():
        t=open("C:\Users\office\Desktop\Files\Thorium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b107():
        t=open("C:\Users\office\Desktop\Files\Protactinium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b108():
        t=open("C:\Users\office\Desktop\Files\Uranium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="74",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b109():
        t=open("C:\Users\office\Desktop\Files\Neptunium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b110():
        t=open("C:\Users\office\Desktop\Files\Plutonium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="71",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b111():
        t=open("C:\Users\office\Desktop\Files\Americium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b112():
        t=open("C:\Users\office\Desktop\Files\Curium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="73",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b113():
        t=open("C:\Users\office\Desktop\Files\Berkelium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="70",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b114():
        t=open("C:\Users\office\Desktop\Files\Californium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b115():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Einsteinium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b116():
        t=open("D:\Study Material\Projects\Class XI Python Project\Files\Fermium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="69",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b117():
        t=open("C:\Users\office\Desktop\Files\Mendelevium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="65",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
    def b118():
        t=open("C:\Users\office\Desktop\Files\Nobelium.txt",'r')
        root = Tk()
        text = Text(root)
        text=Text(root,width="64",height="40")
        text.insert(INSERT,t.read())
        text.pack()
        root.mainloop()
        
    # Group 1
    a1=Button(top,text="H",bg="light blue",relief="solid",width="4",height="2",command=b1)
    a2=Button(top,text="Li",bg="light blue",relief="solid",width="4",height="2",command=b2)
    a3=Button(top,text="Na",bg="light blue",relief="solid",width="4",height="2",command=b3)
    a4=Button(top,text="K",bg="light blue",relief="solid",width="4",height="2",command=b4)
    a5=Button(top,text="Rb",bg="light blue",relief="solid",width="4",height="2",command=b5)
    a6=Button(top,text="Cs",bg="light blue",relief="solid",width="4",height="2",command=b6)
    a7=Button(top,text="Fr",bg="light blue",relief="solid",width="4",height="2",command=b7)
    # Group 2
    a8=Button(top,text="Be",bg="light blue",relief="solid",width="4",height="2",command=b8)
    a9=Button(top,text="Mg",bg="light blue",relief="solid",width="4",height="2",command=b9)
    a10=Button(top,text="Ca",bg="light blue",relief="solid",width="4",height="2",command=b10)
    a11=Button(top,text="Sr",bg="light blue",relief="solid",width="4",height="2",command=b11)
    a12=Button(top,text="Ba",bg="light blue",relief="solid",width="4",height="2",command=b12)
    a13=Button(top,text="Ra",bg="light blue",relief="solid",width="4",height="2",command=b13)
    # Group 3
    a14=Button(top,text="Sc",bg="yellow",relief="solid",width="4",height="2",command=b14)
    a15=Button(top,text="Y",bg="yellow",relief="solid",width="4",height="2",command=b15)
    a16=Button(top,text="Lu",bg="yellow",relief="solid",width="4",height="2",command=b16)
    a17=Button(top,text="Lr",bg="yellow",relief="solid",width="4",height="2",command=b17)
    # Group 4
    a18=Button(top,text="Ti",bg="yellow",relief="solid",width="4",height="2",command=b18)
    a19=Button(top,text="Zr",bg="yellow",relief="solid",width="4",height="2",command=b19)
    a20=Button(top,text="Hf",bg="yellow",relief="solid",width="4",height="2",command=b20)
    a21=Button(top,text="Rf",bg="yellow",relief="solid",width="4",height="2",command=b21)
    #group 5
    a22=Button(top,text="V",bg="yellow",relief="solid",width="4",height="2",command=b22)
    a23=Button(top,text="Nb",bg="yellow",relief="solid",width="4",height="2",command=b23)
    a24=Button(top,text="Ta",bg="yellow",relief="solid",width="4",height="2",command=b24)
    a25=Button(top,text="Db",bg="yellow",relief="solid",width="4",height="2",command=b25)
    # Group 6
    a26=Button(top,text="Cr",bg="yellow",relief="solid",width="4",height="2",command=b26)
    a27=Button(top,text="Mo",bg="yellow",relief="solid",width="4",height="2",command=b27)
    a28=Button(top,text="W",bg="yellow",relief="solid",width="4",height="2",command=b28)
    a29=Button(top,text="Sg",bg="yellow",relief="solid",width="4",height="2",command=b29)
    # Group 7
    a30=Button(top,text="Mn",bg="yellow",relief="solid",width="4",height="2",command=b30)
    a31=Button(top,text="Tc",bg="yellow",relief="solid",width="4",height="2",command=b31)
    a32=Button(top,text="Re",bg="yellow",relief="solid",width="4",height="2",command=b32)
    a33=Button(top,text="Bh",bg="yellow",relief="solid",width="4",height="2",command=b33)
    # Group 8
    a34=Button(top,text="Fe",bg="yellow",relief="solid",width="4",height="2",command=b34)
    a35=Button(top,text="Ru",bg="yellow",relief="solid",width="4",height="2",command=b35)
    a36=Button(top,text="Os",bg="yellow",relief="solid",width="4",height="2",command=b36)
    a37=Button(top,text="Hs",bg="yellow",relief="solid",width="4",height="2",command=b37)
    # Group 9
    a38=Button(top,text="Co",bg="yellow",relief="solid",width="4",height="2",command=b38)
    a39=Button(top,text="Rh",bg="yellow",relief="solid",width="4",height="2",command=b39)
    a40=Button(top,text="Ir",bg="yellow",relief="solid",width="4",height="2",command=b40)
    a41=Button(top,text="Mt",bg="yellow",relief="solid",width="4",height="2",command=b41)
    # Group 10
    a42=Button(top,text="Ni",bg="yellow",relief="solid",width="4",height="2",command=b42)
    a43=Button(top,text="Pd",bg="yellow",relief="solid",width="4",height="2",command=b43)
    a44=Button(top,text="Pt",bg="yellow",relief="solid",width="4",height="2",command=b44)
    a45=Button(top,text="Ds",bg="yellow",relief="solid",width="4",height="2",command=b45)
    # Group 11
    a46=Button(top,text="Cu",bg="yellow",relief="solid",width="4",height="2",command=b46)
    a47=Button(top,text="Ag",bg="yellow",relief="solid",width="4",height="2",command=b47)
    a48=Button(top,text="Au",bg="yellow",relief="solid",width="4",height="2",command=b48)
    a49=Button(top,text="Rg",bg="yellow",relief="solid",width="4",height="2",command=b49)
    # Group 12
    a50=Button(top,text="Zn",bg="yellow",relief="solid",width="4",height="2",command=b50)
    a51=Button(top,text="Cd",bg="yellow",relief="solid",width="4",height="2",command=b51)
    a52=Button(top,text="Hg",bg="yellow",relief="solid",width="4",height="2",command=b52)
    a53=Button(top,text="Cn",bg="yellow",relief="solid",width="4",height="2",command=b53)
    # Group 13
    a54=Button(top,text="B",bg="light green",relief="solid",width="4",height="2",command=b54)
    a55=Button(top,text="Al",bg="light green",relief="solid",width="4",height="2",command=b55)
    a56=Button(top,text="Ga",bg="light green",relief="solid",width="4",height="2",command=b56)
    a57=Button(top,text="In",bg="light green",relief="solid",width="4",height="2",command=b57)
    a58=Button(top,text="Tl",bg="light green",relief="solid",width="4",height="2",command=b58)
    a59=Button(top,text="Uut",bg="light green",relief="solid",width="4",height="2",command=b59)
    # Group 14
    a60=Button(top,text="C",bg="light green",relief="solid",width="4",height="2",command=b60)
    a61=Button(top,text="Si",bg="light green",relief="solid",width="4",height="2",command=b61)
    a62=Button(top,text="Ge",bg="light green",relief="solid",width="4",height="2",command=b62)
    a63=Button(top,text="Sn",bg="light green",relief="solid",width="4",height="2",command=b63)
    a64=Button(top,text="Pb",bg="light green",relief="solid",width="4",height="2",command=b64)
    a65=Button(top,text="Fl",bg="light green",relief="solid",width="4",height="2",command=b65)
    # Group 15
    a66=Button(top,text="N",bg="light green",relief="solid",width="4",height="2",command=b66)
    a67=Button(top,text="P",bg="light green",relief="solid",width="4",height="2",command=b67)
    a68=Button(top,text="As",bg="light green",relief="solid",width="4",height="2",command=b68)
    a69=Button(top,text="Sb",bg="light green",relief="solid",width="4",height="2",command=b69)
    a70=Button(top,text="Bi",bg="light green",relief="solid",width="4",height="2",command=b70)
    a71=Button(top,text="Uup",bg="light green",relief="solid",width="4",height="2",command=b71)
    # Group 16
    a72=Button(top,text="O",bg="light green",relief="solid",width="4",height="2",command=b72)
    a73=Button(top,text="S",bg="light green",relief="solid",width="4",height="2",command=b73)
    a74=Button(top,text="Se",bg="light green",relief="solid",width="4",height="2",command=b74)
    a75=Button(top,text="Te",bg="light green",relief="solid",width="4",height="2",command=b75)
    a76=Button(top,text="Po",bg="light green",relief="solid",width="4",height="2",command=b76)
    a77=Button(top,text="Lv",bg="light green",relief="solid",width="4",height="2",command=b77)
    # Group 17
    a78=Button(top,text="F",bg="light green",relief="solid",width="4",height="2",command=b78)
    a79=Button(top,text="Cl",bg="light green",relief="solid",width="4",height="2",command=b79)
    a80=Button(top,text="Br",bg="light green",relief="solid",width="4",height="2",command=b80)
    a81=Button(top,text="I",bg="light green",relief="solid",width="4",height="2",command=b81)
    a82=Button(top,text="At",bg="light green",relief="solid",width="4",height="2",command=b82)
    a83=Button(top,text="Uus",bg="light green",relief="solid",width="4",height="2",command=b83)
    # Group 18
    a84=Button(top,text="He",bg="light green",relief="solid",width="4",height="2",command=b84)
    a85=Button(top,text="Ne",bg="light green",relief="solid",width="4",height="2",command=b85)
    a86=Button(top,text="Ar",bg="light green",relief="solid",width="4",height="2",command=b86)
    a87=Button(top,text="Kr",bg="light green",relief="solid",width="4",height="2",command=b87)
    a88=Button(top,text="Xe",bg="light green",relief="solid",width="4",height="2",command=b88)
    a89=Button(top,text="Rn",bg="light green",relief="solid",width="4",height="2",command=b89)
    a90=Button(top,text="Uuo",bg="light green",relief="solid",width="4",height="2",command=b90)
    # Lanthanoids
    a91=Button(top,text="La",bg="pink",relief="solid",width="4",height="2",command=b91)
    a92=Button(top,text="Ce",bg="pink",relief="solid",width="4",height="2",command=b92)
    a93=Button(top,text="Pr",bg="pink",relief="solid",width="4",height="2",command=b93)
    a94=Button(top,text="Nd",bg="pink",relief="solid",width="4",height="2",command=b94)
    a95=Button(top,text="Pm",bg="pink",relief="solid",width="4",height="2",command=b95)
    a96=Button(top,text="Sm",bg="pink",relief="solid",width="4",height="2",command=b96)
    a97=Button(top,text="Eu",bg="pink",relief="solid",width="4",height="2",command=b97)
    a98=Button(top,text="Gd",bg="pink",relief="solid",width="4",height="2",command=b98)
    a99=Button(top,text="Tb",bg="pink",relief="solid",width="4",height="2",command=b99)
    a100=Button(top,text="Dy",bg="pink",relief="solid",width="4",height="2",command=b100)
    a101=Button(top,text="Ho",bg="pink",relief="solid",width="4",height="2",command=b101)
    a102=Button(top,text="Er",bg="pink",relief="solid",width="4",height="2",command=b102)
    a103=Button(top,text="Tm",bg="pink",relief="solid",width="4",height="2",command=b103)
    a104=Button(top,text="Yb",bg="pink",relief="solid",width="4",height="2",command=b104)

    # Actinoids
    a105=Button(top,text="Ac",bg="pink",relief="solid",width="4",height="2",command=b105)
    a106=Button(top,text="Th",bg="pink",relief="solid",width="4",height="2",command=b106)
    a107=Button(top,text="Pa",bg="pink",relief="solid",width="4",height="2",command=b107)
    a108=Button(top,text="U",bg="pink",relief="solid",width="4",height="2",command=b108)
    a109=Button(top,text="Np",bg="pink",relief="solid",width="4",height="2",command=b109)
    a110=Button(top,text="Pu",bg="pink",relief="solid",width="4",height="2",command=b110)
    a111=Button(top,text="Am",bg="pink",relief="solid",width="4",height="2",command=b111)
    a112=Button(top,text="Cm",bg="pink",relief="solid",width="4",height="2",command=b112)
    a113=Button(top,text="Bk",bg="pink",relief="solid",width="4",height="2",command=b113)
    a114=Button(top,text="Cf",bg="pink",relief="solid",width="4",height="2",command=b114)
    a115=Button(top,text="Es",bg="pink",relief="solid",width="4",height="2",command=b115)
    a116=Button(top,text="Fm",bg="pink",relief="solid",width="4",height="2",command=b116)
    a117=Button(top,text="Md",bg="pink",relief="solid",width="4",height="2",command=b117)
    a118=Button(top,text="No",bg="pink",relief="solid",width="4",height="2",command=b118)

    p=Label(top,relief="solid",bg="violet",text="Lanthanoids",font="25")
    q=Label(top,relief="solid",bg="violet",text="Actinoids",font="25")
    r=Label(top,relief="solid",bg="orange",text="MODERN PERIODIC TABLE",bd="5",font=("Algerian",42,"bold"),height="1",width="20")
    s=Label(top,relief="solid",bg="violet",text="s - BLOCK",font="bold")
    t=Label(top,relief="solid",bg="violet",text="p - BLOCK",font="bold")
    u=Label(top,relief="solid",bg="violet",text="d - BLOCK",font="bold")
    v=Label(top,relief="solid",bg="violet",text="f - BLOCK",font="bold")
    x=Button(top,relief="groove",text="Exit",command=cont3)
    # Group 1
    a1.pack()
    a1.place(x=30,y=150)
    a2.pack()
    a2.place(x=30,y=200)
    a3.pack()
    a3.place(x=30,y=250)
    a4.pack()
    a4.place(x=30,y=300)
    a5.pack()
    a5.place(x=30,y=350)
    a6.pack()
    a6.place(x=30,y=400)
    a7.pack()
    a7.place(x=30,y=450)
    # Group 2
    a8.pack()
    a8.place(x=90,y=200)
    a9.pack()
    a9.place(x=90,y=250)
    a10.pack()
    a10.place(x=90,y=300)
    a11.pack()
    a11.place(x=90,y=350)
    a12.pack()
    a12.place(x=90,y=400)
    a13.pack()
    a13.place(x=90,y=450)
    # Group 3
    a14.pack()
    a14.place(x=200,y=300)
    a15.pack()
    a15.place(x=200,y=350)
    a16.pack()
    a16.place(x=200,y=400)
    a17.pack()
    a17.place(x=200,y=450)
    # Group 4
    a18.pack()
    a18.place(x=260,y=300)
    a19.pack()
    a19.place(x=260,y=350)
    a20.pack()
    a20.place(x=260,y=400)
    a21.pack()
    a21.place(x=260,y=450)
    # Group 5
    a22.pack()
    a22.place(x=320,y=300)
    a23.pack()
    a23.place(x=320,y=350)
    a24.pack()
    a24.place(x=320,y=400)
    a25.pack()
    a25.place(x=320,y=450)
    # Group 6
    a26.pack()
    a26.place(x=380,y=300)
    a27.pack()
    a27.place(x=380,y=350)
    a28.pack()
    a28.place(x=380,y=400)
    a29.pack()
    a29.place(x=380,y=450)
    # Group 7
    a30.pack()
    a30.place(x=440,y=300)
    a31.pack()
    a31.place(x=440,y=350)
    a32.pack()
    a32.place(x=440,y=400)
    a33.pack()
    a33.place(x=440,y=450)
    # Group 8
    a34.pack()
    a34.place(x=500,y=300)
    a35.pack()
    a35.place(x=500,y=350)
    a36.pack()
    a36.place(x=500,y=400)
    a37.pack()
    a37.place(x=500,y=450)
    # Group 9
    a38.pack()
    a38.place(x=560,y=300)
    a39.pack()
    a39.place(x=560,y=350)
    a40.pack()
    a40.place(x=560,y=400)
    a41.pack()
    a41.place(x=560,y=450)
    # Group 10
    a42.pack()
    a42.place(x=620,y=300)
    a43.pack()
    a43.place(x=620,y=350)
    a44.pack()
    a44.place(x=620,y=400)
    a45.pack()
    a45.place(x=620,y=450)
    # Group 11
    a46.pack()
    a46.place(x=680,y=300)
    a47.pack()
    a47.place(x=680,y=350)
    a48.pack()
    a48.place(x=680,y=400)
    a49.pack()
    a49.place(x=680,y=450)
    # Group 12
    a50.pack()
    a50.place(x=740,y=300)
    a51.pack()
    a51.place(x=740,y=350)
    a52.pack()
    a52.place(x=740,y=400)
    a53.pack()
    a53.place(x=740,y=450)
    # Group 13
    a54.pack()
    a54.place(x=850,y=200)
    a55.pack()
    a55.place(x=850,y=250)
    a56.pack()
    a56.place(x=850,y=300)
    a57.pack()
    a57.place(x=850,y=350)
    a58.pack()
    a58.place(x=850,y=400)
    a59.pack()
    a59.place(x=850,y=450)
    # Group 14
    a60.pack()
    a60.place(x=910,y=200)
    a61.pack()
    a61.place(x=910,y=250)
    a62.pack()
    a62.place(x=910,y=300)
    a63.pack()
    a63.place(x=910,y=350)
    a64.pack()
    a64.place(x=910,y=400)
    a65.pack()
    a65.place(x=910,y=450)
    # Group 15
    a66.pack()
    a66.place(x=970,y=200)
    a67.pack()
    a67.place(x=970,y=250)
    a68.pack()
    a68.place(x=970,y=300)
    a69.pack()
    a69.place(x=970,y=350)
    a70.pack()
    a70.place(x=970,y=400)
    a71.pack()
    a71.place(x=970,y=450)
    # Group 16
    a72.pack()
    a72.place(x=1030,y=200)
    a73.pack()
    a73.place(x=1030,y=250)
    a74.pack()
    a74.place(x=1030,y=300)
    a75.pack()
    a75.place(x=1030,y=350)
    a76.pack()
    a76.place(x=1030,y=400)
    a77.pack()
    a77.place(x=1030,y=450)
    # Group 17
    a78.pack()
    a78.place(x=1090,y=200)
    a79.pack()
    a79.place(x=1090,y=250)
    a80.pack()
    a80.place(x=1090,y=300)
    a81.pack()
    a81.place(x=1090,y=350)
    a82.pack()
    a82.place(x=1090,y=400)
    a83.pack()
    a83.place(x=1090,y=450)
    # Group 18
    a84.pack()
    a84.place(x=1150,y=150)
    a85.pack()
    a85.place(x=1150,y=200)
    a86.pack()
    a86.place(x=1150,y=250)
    a87.pack()
    a87.place(x=1150,y=300)
    a88.pack()
    a88.place(x=1150,y=350)
    a89.pack()
    a89.place(x=1150,y=400)
    a90.pack()
    a90.place(x=1150,y=450)
    # Lanthanoids
    a91.pack()
    a91.place(x=200,y=550)
    a92.pack()
    a92.place(x=260,y=550)
    a93.pack()
    a93.place(x=320,y=550)
    a94.pack()
    a94.place(x=380,y=550)
    a95.pack()
    a95.place(x=440,y=550)
    a96.pack()
    a96.place(x=500,y=550)
    a97.pack()
    a97.place(x=560,y=550)
    a98.pack()
    a98.place(x=620,y=550)
    a99.pack()
    a99.place(x=680,y=550)
    a100.pack()
    a100.place(x=740,y=550)
    a101.pack()
    a101.place(x=850,y=550)
    a102.pack()
    a102.place(x=910,y=550)
    a103.pack()
    a103.place(x=970,y=550)
    a104.pack()
    a104.place(x=1030,y=550)
    # Actinoids
    a105.pack()
    a105.place(x=200,y=600)
    a106.pack()
    a106.place(x=260,y=600)
    a107.pack()
    a107.place(x=320,y=600)
    a108.pack()
    a108.place(x=380,y=600)
    a109.pack()
    a109.place(x=440,y=600)
    a110.pack()
    a110.place(x=500,y=600)
    a111.pack()
    a111.place(x=560,y=600)
    a112.pack()
    a112.place(x=620,y=600)
    a113.pack()
    a113.place(x=680,y=600)
    a114.pack()
    a114.place(x=740,y=600)
    a115.pack()
    a115.place(x=850,y=600)
    a116.pack()
    a116.place(x=910,y=600)
    a117.pack()
    a117.place(x=970,y=600)
    a118.pack()
    a118.place(x=1030,y=600)


    p.pack()
    p.place(x=30,y=560)
    q.pack()
    q.place(x=30,y=610)
    r.pack()
    r.place(x=275,y=10)
    s.pack()
    s.place(x=50,y=110)
    t.pack()
    t.place(x=980,y=110)
    u.pack()
    u.place(x=445,y=260)
    v.pack()
    v.place(x=475,y=515)
    x.pack()
    x.place(x=1100,y=650)
    top.mainloop()
# Thank you page
def cont3():
    time.sleep(1)
    import tkMessageBox
    thank=Tk()
    thank.configure(height=10000,width=10000)
    c14=Label(thank,text="THANK YOU",font=("ALGERIAN",110,"bold"),fg="red",height="2",width="10")
    c14.pack()
    c14.place(x=200,y=200)
    thank.mainloop()

# Information page
def cont1():
    time.sleep(1)
    import tkMessageBox
    intro=Tk()
    intro.configure(height=10000,width=10000)
    c10=Label(intro,text="MODERN PERIODIC TABLE",font=("ALGERIAN",60,),fg="blue",height="1",width="25")
    c11=Text(intro,font=("arial",15),width="100",height="20")
    c11.insert(INSERT,"The periodic table is a tabular arrangement of the chemical elements, organized on the basis of their atomic numbers, electron configurations (electron shell model), and recurring chemical properties.\nElements are presented in order of increasing atomic number (the number of protons in the nucleus).\nThe standard form of the table consists of a grid of elements laid out in 18 columns and 7 rows, with a double row of elements below that.\nThe table can also be deconstructed into four rectangular blocks: the s-block to the left, the p-block to the right, the d-block in the middle, and the f-block below that.\nThe rows of the table are called periods; the columns are called groups, with some of these having names such as halogens or noble gases.\nSince, by definition, a periodic table incorporates recurring trends, any such table can be used to derive relationships between the properties of the elements and predict the properties of new, yet to be discovered or synthesized, elements.\nAs a result, a periodic table�whether in the standard form or some other variant�provides a useful framework for analyzing chemical behavior, and such tables are widely used in chemistry and other sciences.")
    c12=Button(intro,text="Press To Continue",command=cont2,height="2",relief="solid",width="20")
    c10.pack()
    c10.place(x=35,y=20)
    c11.pack()
    c11.place(x=80,y=140)
    c12.pack()
    c12.place(x=1100,y=650)
    intro.mainloop()

# Introduction page
def cont():
    time.sleep(1)
    import tkMessageBox
    topic=Tk()
    topic.configure(height=10000,width=10000)
    c3=Label(topic,text="CS  PROJECT",font=("ALGERIAN",60,),fg="blue",height="1",width="10")
    c4=Label(topic,text="MODERN PERIODIC TABLE",font=("ALGERIAN",60,),fg="blue",height="1",width="20")
    c5=Label(topic,text="NAME: Vikas  ",font=("ALGERIAN",45,),anchor="w",fg="green",height="1",width="25")
    c6=Label(topic,text="CLASS: XI-B",font=("ALGERIAN",45,),anchor="w",fg="green",height="1",width="25")
    c7=Label(topic,text="ROLL NO: 30",font=("ALGERIAN",45,),anchor="w",fg="green",height="1",width="25")
    c8=Label(topic,text="SUBMITTED TO: Dr. RAJU RANJAN",font=("ALGERIAN",45,),anchor="w",fg="green",height="1",width="26")
    c9=Button(topic,text="Press To Continue",command=cont1,height="2",relief="solid",width="20")
    c3.pack()
    c3.place(x=350,y=20)
    c4.pack()
    c4.place(x=130,y=120)
    c5.pack()
    c5.place(x=100,y=220)
    c6.pack()
    c6.place(x=100,y=320)
    c7.pack()
    c7.place(x=100,y=420)
    c8.pack()
    c8.place(x=100,y=520)
    c9.pack()
    c9.place(x=1100,y=650)
    topic.mainloop()
    
def con():
    d1=c3.get()
    d1=str(d1)
    if(d1=="vikas"):
        cont()
    if(d1==""):
        import tkMessageBox
        tkMessageBox.showinfo("Invalid","Please Enter the password")
    else:
        import tkMessageBox
        tkMessageBox.showinfo("Invalid Password","Please Try Again")
       
# Welcome page
import time
from Tkinter import *
import tkMessageBox
wel=Tk()
wel.configure(height=10000,width=10000)
c1=Label(wel,text="WELCOME",font=("ALGERIAN",110,"bold"),fg="red",height="2",width="10")
c2=Label(wel,text="Enter password",height="2",width="20")
c3=Entry(wel,bd=4,show="*")
c4=Button(wel,text="OK",relief="groove",command=con)
c1.pack()
c1.place(x=200,y=200)
c2.pack()
c2.place(x=970,y=600)
c3.pack()
c3.place(x=1100,y=605)
c4.pack
c4.place(x=1145,y=645)
wel.mainloop()


